# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfosysMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfosysMVVM
  # API web service
  pod 'Alamofire', '~> 4.7'
  pod 'Alamofire-SwiftyJSON'
  
  # Image
  pod 'SDWebImage', '~> 5.0'


  target 'InfosysMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
